### ISSUE TITLE
Wrong description

### ISSUE THREAD

**Issue by srichakradhar** [software-engineering-project-1/artificial-neural-networks-exp5-team3#1]
The description says - "you can choose at most two states as minimum".

But user should be able to select only two states as minimum energy states. No more, no less.
![image](https://cloud.githubusercontent.com/assets/1732922/12624011/d3bc4152-c552-11e5-8d0f-82d5abfc1ee0.png)

Resolve it by changing the description to "Choose 2 states which you intend to make as minimum energy states. Make sure of them being apart for a Hamming distance more than 1." and by alerting the user when a selection of more than 2 states has been made.

We can also have color coding for the alert:
1. RED: when no state is selected and when more than 2 states are selected. In this state, it says: "Select two states"
2. YELLOW: When one state is selected. In this state, it says: "Select one more state."
3. GREEN: when only 2 states are selected. In this state, it shows the hamming distance.

The same color code applies to hamming distance as well... RED if < 1 or > 1, else GREEN. It should be hidden when 2 states are not selected.

**Comment by rsk1coder99** [comment]
done, color coding left

**Comment by rsk1coder99** [comment]
done completely, with only descriptive errors
