### ISSUE TITLE
"wrong choice" warning is misleading

### ISSUE THREAD

**Issue by srichakradhar** [software-engineering-project-1/artificial-neural-networks-exp5-team3#2]
The warning says: "Wrong choice:: Press button to enter again". But both the inputs and the displayed button are considered buttons.
![image](https://cloud.githubusercontent.com/assets/1732922/12622594/16dc1946-c54c-11e5-9c07-b137399abe32.png)
Resolve it by removing the "click" button. Allow the user to select the buttons after showing the warning.

**Comment by rsk1coder99** [comment]
Fixed
