### ISSUE TITLE
Cannot deselect a selected button.

### ISSUE THREAD

**Issue by srichakradhar** [software-engineering-project-1/artificial-neural-networks-exp5-team3#3]
User is not able to deselect the buttons once selected, making it difficult to undo the selection of any buttons selected by mistake.
![image](https://cloud.githubusercontent.com/assets/1732922/12622526/d333a4e8-c54b-11e5-9398-d464081154a2.png)
Resolve it by adding the toggle functionality to the button.

**Comment by rsk1coder99** [comment]
resolved. Toggle functionality introduced
