### ISSUE TITLE
Slider for adjusting weights and thresholds

### ISSUE THREAD

**Issue by srichakradhar** [software-engineering-project-1/artificial-neural-networks-exp5-team3#4]
With the sliders currently being used for adjusting weights and thresholds, only discrete values can be selected in steps of 0.1, which is not the ideal state, most often.
![image](https://cloud.githubusercontent.com/assets/1732922/12625102/37285c6c-c558-11e5-9f49-3d5d4f152838.png)
Resolve it by using a (pseudo) continuous slider, with a resolution of at least 0.001 units.

**Comment by rsk1coder99** [comment]
Fixed. New precision = 0.01
